import { ApiProperty } from '@nestjs/swagger';
import {
  INCIDENT_EVENT_KINDS,
  INCIDENT_SEVERITIES,
  INCIDENT_SOURCES,
  INCIDENT_STATUSES,
  INCIDENT_TYPES,
  type Incident,
  type IncidentDetail,
  type IncidentEvent,
  type IncidentEventKind,
  type IncidentSeverity,
  type IncidentSource,
  type IncidentStatus,
  type IncidentType,
  type LngLat,
} from '@occ/contracts';

/** OpenAPI response shapes. `implements` keeps them in lockstep with `@occ/contracts`. */

export class IncidentDto implements Incident {
  /** Incident id. */
  @ApiProperty({ format: 'uuid' })
  id: string;

  @ApiProperty({ example: 'INC-000042' })
  code: string;

  /** What happened. */
  @ApiProperty({ enum: INCIDENT_TYPES })
  type: IncidentType;

  /** From least to most urgent: `low`, `medium`, `high`, `critical`. */
  @ApiProperty({ enum: INCIDENT_SEVERITIES })
  severity: IncidentSeverity;

  /** `open`: not picked up yet. `acknowledged`: an operator is handling it. `resolved`: closed. */
  @ApiProperty({ enum: INCIDENT_STATUSES })
  status: IncidentStatus;

  @ApiProperty({ example: 'Door forced open — service corridor' })
  title: string;

  @ApiProperty({ type: String, nullable: true })
  description: string | null;

  /** Zone the incident is in. */
  @ApiProperty({ format: 'uuid' })
  zoneId: string;

  @ApiProperty({
    description: 'Location as [lng, lat]. The zone centre when none was given at report time.',
    type: [Number],
    minItems: 2,
    maxItems: 2,
  })
  position: LngLat;

  /** `operator`: reported by a person. `simulator`: generated by the demo incident simulator. */
  @ApiProperty({ enum: INCIDENT_SOURCES })
  source: IncidentSource;

  /** When the incident was reported. */
  @ApiProperty({ format: 'date-time' })
  reportedAt: string;

  /** When an operator acknowledged it. `null` until then. */
  @ApiProperty({ type: String, format: 'date-time', nullable: true })
  acknowledgedAt: string | null;

  /** When it was resolved. `null` until then. */
  @ApiProperty({ type: String, format: 'date-time', nullable: true })
  resolvedAt: string | null;
}

export class IncidentEventDto implements IncidentEvent {
  @ApiProperty({ format: 'uuid' })
  id: string;

  /** The state change this entry records: `reported`, `acknowledged` or `resolved`. */
  @ApiProperty({ enum: INCIDENT_EVENT_KINDS })
  kind: IncidentEventKind;

  @ApiProperty({ type: String, nullable: true })
  note: string | null;

  @ApiProperty({ format: 'date-time' })
  at: string;
}

export class IncidentDetailDto extends IncidentDto implements IncidentDetail {
  /** Every state change, oldest first. */
  @ApiProperty({ type: [IncidentEventDto] })
  timeline: IncidentEventDto[];
}
